[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]

# openwrt target
[target.arm-unknown-linux-musleabihf]
ar = "arm-openwrt-linux-muslgnueabi-ar"
linker = "arm-linux-musleabihf-gcc"

# make programs faster
[profile.release]
lto = 'thin'

[profile.bench]
codegen-units = 1

[profile.dev]
split-debuginfo = "unpacked"
codegen-units = 256

[build]
rustc-wrapper = "sccache"

[alias]
b = "build"
br = "build --release"
c = "check"
t = "test"
r = "run"
rr = "run --release"

