[tool.ruff.lint]
select = [
  "A",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "COM",
  "CPY",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "LOG",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "TCH",
  "TD",
  "TID",
  "TRIO",
  "TRY",
  "UP",
  "YTT",
]

ignore = [
    "COM812",
    "E501",
    "INP001",
    "PLR2004",
    "PTH122",
    "PTH123",
    "S101",
    "S310",
    "S314",
    "S603",
    "S607",
]

[tool.ruff.format]
quote-style = "single"
