[tool.ruff.lint]
select = [
  "A",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "COM",
  "CPY",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "LOG",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "TCH",
  "TD",
  "TID",
  "TRIO",
  "TRY",
  "UP",
  "YTT",

  # pydocstyle
  "D101", # undocumented-public-class",
  "D103", # "undocumented-public-function",
  "D102", # "undocumented-public-method",

]

ignore = [
    "COM812",  # "missing-trailing-comma",
    "E501",    # "line-too-long",
    "INP001",  # "implicit-namespace-package",
    "ISC001",  # "single-line-implicit-string-concatenation",
    "PLR2004", # "magic-value-comparison",
    "PTH122",  # "os-path-splitext",
    "PTH123",  # "builtin-open",
    "S101",    # "assert",
    "S310",    # "suspicious-url-open-usage",
    "S314",    # "suspicious-xml-element-tree-usage",
    "S603",    # "subprocess-without-shell-equals-true",
    "S607",    # "start-process-with-partial-path",
]

[tool.ruff.format]
quote-style = "single"
